#!/usr/bin/env python3
"""
setup.py - Configuration wizard for Days to Thing Tracker

Usage:
    python setup.py              # Interactive setup
    python setup.py --check      # Verify configuration
    python setup.py --reset      # Reset to defaults
"""

import os
import sys
import subprocess
import shutil
import getpass
from pathlib import Path
from typing import Optional

# Constants
PROJECT_ROOT = Path(__file__).parent.absolute()
ENV_FILE = PROJECT_ROOT / ".env"
ENV_EXAMPLE = PROJECT_ROOT / ".env.example"
DOCKER_STATE_DIR = PROJECT_ROOT / ".docker" / "tailscale" / "state"
DATA_DIR = PROJECT_ROOT / "data"


def print_banner():
    """Display setup banner."""
    print("\n" + "=" * 55)
    print("  Days to Thing Tracker - Setup Wizard")
    print("=" * 55 + "\n")


def print_step(step: int, message: str):
    """Print a step message."""
    print(f"\n[Step {step}] {message}")
    print("-" * 40)


def check_command(cmd: str) -> bool:
    """Check if a command exists."""
    return shutil.which(cmd) is not None


def check_docker_compose() -> bool:
    """Check if docker compose (v2) is available."""
    try:
        result = subprocess.run(
            ["docker", "compose", "version"],
            capture_output=True,
            text=True
        )
        return result.returncode == 0
    except Exception:
        return False


def check_dependencies() -> bool:
    """Verify required tools are installed."""
    print_step(1, "Checking dependencies")

    required = [
        ("docker", "Docker"),
        ("node", "Node.js"),
        ("npm", "npm"),
    ]

    all_found = True
    for cmd, name in required:
        if check_command(cmd):
            print(f"  [OK] {name}")
        else:
            print(f"  [MISSING] {name}")
            all_found = False

    # Check docker compose
    if check_docker_compose():
        print(f"  [OK] Docker Compose")
    else:
        print(f"  [MISSING] Docker Compose (v2)")
        all_found = False

    if not all_found:
        print("\nPlease install missing dependencies and run setup again.")
        return False

    print("\nAll dependencies found!")
    return True


def prompt(message: str, default: Optional[str] = None) -> str:
    """Prompt user for input with optional default."""
    if default:
        result = input(f"{message} [{default}]: ").strip()
        return result if result else default
    return input(f"{message}: ").strip()


def prompt_yes_no(message: str, default: bool = True) -> bool:
    """Prompt for yes/no input."""
    default_str = "Y/n" if default else "y/N"
    result = input(f"{message} ({default_str}): ").strip().lower()
    if not result:
        return default
    return result in ("y", "yes")


def read_env_file() -> dict:
    """Read existing .env file if it exists."""
    config = {}
    if ENV_FILE.exists():
        with open(ENV_FILE, "r") as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith("#") and "=" in line:
                    key, value = line.split("=", 1)
                    config[key.strip()] = value.strip()
    return config


def configure_environment():
    """Create .env file with user configuration."""
    print_step(2, "Configuring environment")

    existing_config = read_env_file()
    config = {}

    # Database URL (default for SQLite)
    config["DATABASE_URL"] = "file:./data/tasks.db"
    print(f"Database: SQLite at ./data/tasks.db")

    # Tailscale Auth Key
    print("\nTailscale Setup:")
    print("  1. Go to https://login.tailscale.com/admin/settings/keys")
    print("  2. Generate a new auth key")
    print("     - Recommended: Reusable key with tags")
    print("     - Suggested tag: tag:server")
    print("  3. Copy the key (starts with 'tskey-auth-')")

    existing_key = existing_config.get("TS_AUTHKEY", "")
    if existing_key:
        masked = existing_key[:12] + "..." if len(existing_key) > 15 else "***"
        print(f"\nExisting Tailscale key found: {masked}")
        if prompt_yes_no("Keep existing key?", default=True):
            config["TS_AUTHKEY"] = existing_key
        else:
            config["TS_AUTHKEY"] = getpass.getpass("Enter new Tailscale Auth Key: ")
    else:
        config["TS_AUTHKEY"] = getpass.getpass("\nEnter Tailscale Auth Key: ")

    if not config["TS_AUTHKEY"]:
        print("\nWARNING: No Tailscale key provided.")
        print("You can add it later by editing .env file")
        config["TS_AUTHKEY"] = ""

    # Write .env file
    env_lines = [
        "# Auto-generated by setup.py",
        "# Do not commit this file to version control",
        "",
        "# Tailscale Auth Key",
        f"TS_AUTHKEY={config['TS_AUTHKEY']}",
        "",
        "# Database URL",
        f"DATABASE_URL={config['DATABASE_URL']}",
    ]

    with open(ENV_FILE, "w") as f:
        f.write("\n".join(env_lines) + "\n")

    # Set restrictive permissions
    os.chmod(ENV_FILE, 0o600)

    print(f"\nConfiguration saved to {ENV_FILE}")


def create_directories():
    """Create necessary directories."""
    print_step(3, "Creating directories")

    directories = [
        (DOCKER_STATE_DIR, "Tailscale state"),
        (DATA_DIR, "Database storage"),
    ]

    for directory, description in directories:
        directory.mkdir(parents=True, exist_ok=True)
        print(f"  Created: {directory} ({description})")


def install_dependencies():
    """Install npm dependencies."""
    print_step(4, "Installing dependencies")

    if (PROJECT_ROOT / "node_modules").exists():
        print("  node_modules already exists")
        if not prompt_yes_no("  Reinstall dependencies?", default=False):
            return

    print("  Running npm install...")
    result = subprocess.run(
        ["npm", "install"],
        cwd=PROJECT_ROOT,
        capture_output=True,
        text=True
    )

    if result.returncode != 0:
        print(f"  ERROR: npm install failed")
        print(result.stderr)
        sys.exit(1)

    print("  Dependencies installed successfully")


def initialize_database():
    """Run Prisma migrations."""
    print_step(5, "Initializing database")

    # Generate Prisma client
    print("  Generating Prisma client...")
    result = subprocess.run(
        ["npx", "prisma", "generate"],
        cwd=PROJECT_ROOT,
        capture_output=True,
        text=True
    )

    if result.returncode != 0:
        print(f"  ERROR: prisma generate failed")
        print(result.stderr)
        sys.exit(1)

    # Run migrations
    print("  Running database migrations...")
    result = subprocess.run(
        ["npx", "prisma", "migrate", "deploy"],
        cwd=PROJECT_ROOT,
        capture_output=True,
        text=True
    )

    if result.returncode != 0:
        print(f"  ERROR: prisma migrate failed")
        print(result.stderr)
        sys.exit(1)

    print("  Database initialized successfully")


def build_containers():
    """Build Docker containers."""
    print_step(6, "Building Docker containers")

    if not prompt_yes_no("Build Docker containers now?", default=True):
        print("  Skipping build. Run 'docker compose build' when ready.")
        return

    print("  Building containers (this may take a few minutes)...")
    result = subprocess.run(
        ["docker", "compose", "build"],
        cwd=PROJECT_ROOT
    )

    if result.returncode != 0:
        print("  WARNING: Build failed. Check the errors above.")
        print("  You can try again with: docker compose build")
    else:
        print("  Containers built successfully!")


def print_next_steps():
    """Display next steps for the user."""
    print("\n" + "=" * 55)
    print("  Setup Complete!")
    print("=" * 55)
    print("""
Next steps:

1. Start the application:
   docker compose up -d

2. View logs:
   docker compose logs -f

3. Access the app (after Tailscale connects):
   http://days-tracker:3000

   Or via Magic DNS:
   http://days-tracker.<your-tailnet>.ts.net:3000

4. Stop the application:
   docker compose down

Development mode (without Docker):
   npm run dev
   (Access at http://localhost:3000)

Useful commands:
   python setup.py --check    Verify configuration
   python setup.py --reset    Reset and reconfigure
""")


def verify_configuration():
    """Check if configuration is valid."""
    print("\n--- Configuration Check ---\n")

    checks = [
        (ENV_FILE.exists(), ".env file exists"),
        (DATA_DIR.exists(), "Data directory exists"),
        (DOCKER_STATE_DIR.exists(), "Tailscale state directory exists"),
        ((PROJECT_ROOT / "prisma" / "schema.prisma").exists(), "Prisma schema exists"),
        ((PROJECT_ROOT / "node_modules").exists(), "Node modules installed"),
        ((PROJECT_ROOT / "docker-compose.yml").exists(), "docker-compose.yml exists"),
    ]

    # Check Tailscale key
    config = read_env_file()
    ts_key = config.get("TS_AUTHKEY", "")
    checks.append((bool(ts_key), "Tailscale auth key configured"))

    all_passed = True
    for passed, description in checks:
        status = "OK" if passed else "MISSING"
        symbol = "[OK]" if passed else "[X]"
        print(f"  {symbol} {description}")
        if not passed:
            all_passed = False

    if all_passed:
        print("\nAll checks passed! You're ready to deploy.")
    else:
        print("\nSome checks failed. Run 'python setup.py' to configure.")

    return all_passed


def reset_configuration():
    """Reset configuration."""
    print("\n--- Reset Configuration ---\n")

    if not prompt_yes_no("This will delete your .env file. Continue?", default=False):
        print("Aborted.")
        return

    if ENV_FILE.exists():
        ENV_FILE.unlink()
        print("Configuration reset. Run 'python setup.py' to reconfigure.")
    else:
        print("No configuration file found.")


def main():
    """Main entry point."""
    if "--check" in sys.argv:
        verify_configuration()
        return

    if "--reset" in sys.argv:
        reset_configuration()
        return

    print_banner()

    if not check_dependencies():
        sys.exit(1)

    configure_environment()
    create_directories()
    install_dependencies()
    initialize_database()
    build_containers()
    print_next_steps()


if __name__ == "__main__":
    main()
